# Generated by Django 2.1.1 on 2018-09-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0004_auto_20180917_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='detail',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
