# Generated by Django 2.1.1 on 2018-09-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0005_auto_20180919_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='summary',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
